baseURL = "https://hugo-starter-site.netlify.app"
languageCode = "en-us"
title = "mathblog"
copyright = "whatever."

rssLimit = 20
staticDir = "static"
canonifyURLs = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  
[author]
	name = "Astle"
	email = "astledsa@gmail.com"

[params]
  description = "Math, something I love and hate"

[markup.goldmark.renderer]
    unsafe = "true"
